---
- name: Manage local kubeadm cluster access
  hosts: local
  tasks:
    - name: Manage SSH access for {{ host_alias }}
      ansible.builtin.blockinfile:
        path: ~/.ssh/config
        marker: "# {mark} k8s {{ host_alias }} ANSIBLE MANAGED BLOCK"
        state: "{{ block_state | default('present') }}"
        create: true
        mode: "0600"
        block: |
          Host {{ host_alias }}
              HostName {{ ip }}
              User root
              Port 22
              StrictHostKeyChecking accept-new
              ForwardAgent no
